### ISSUE TITLE
Totale api /getCart

### ISSUE THREAD

**Issue by StefanoLazzaroni** [SWException/eml-be#1]
![image](https://user-images.githubusercontent.com/44039735/110108862-fac51900-7dac-11eb-9d6b-abd57d3096ca.png)

Deduco che il totale presentato dalla api sia già complessiva di totale costo prodotti + tasse.
In ogni caso sarebbe meglio scriverlo per ovviare dubbi!

**Comment by ivanfurlan** [comment]
> Deduco che il totale presentato dalla api sia già complessiva di totale costo prodotti + tasse.

Sì, è così.
`totale = totaleProdottiIVAEsclusa + IVA` o se preferisci `totale = totaleProdottiIVAInclusa`
`tasse = totaleIVADeiProdottiNelCarrello`
I costi di spedizione non sono inclusi da nessuna parte nel carrello.

> In ogni caso sarebbe meglio scriverlo per ovviare dubbi!

Intendi nella descrizione dell'API? Oggi pomeriggio farò
