### ISSUE TITLE
API GET/products/{id} guasta

### ISSUE THREAD

**Issue by ftrole** [SWException/eml-be#16]
Guardando il log di cloudwatch [(qui)](https://eu-central-1.console.aws.amazon.com/cloudwatch/home?region=eu-central-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Feml-be-dev-getProduct) segnala un errore sul key schema... dunque credo che il problema stia sui metodi della classe Dynamo e sul fatto che la chiave della tabella products è ID + Categoria + prezzo. Non mi viene un modo per fixare se non fare una funzione getFromDB specializzata per i products.
Pareri? @ivanfurlan @mcanovese @micheleveronesi

**Comment by ftrole** [comment]
scusate mi sono accorto ora che michele aveva già aperto la stessa issue

**Comment by ivanfurlan** [comment]
Teoricamente (non ho controllato) il problema è dato perché chiama la funzione di Dynamo che è stata fatta prima di sistemare le chiavi della tabella. Sui products dovrebbe esistere una index Key formata solo dall'id (se non esiste è da fare), e quindi per fare la chiamata sarebbe da usare quella, così per un prodotto basta specificare solo l'id

**Comment by ivanfurlan** [comment]
In tutto se ricordo bene ci sono tre chiavi:
Categoria - id
Categoria - prezzo
Id
