### ISSUE TITLE
Api /getProducts

### ISSUE THREAD

**Issue by StefanoLazzaroni** [SWException/eml-be#2]
![image](https://user-images.githubusercontent.com/44039735/110135050-5bb11900-7dce-11eb-97b9-ba7b0468bb50.png)

Avrebbe senso avere un array di photo al posto di due voci separate? Domanda da rispondere in modo RedBabeliano

**Comment by ivanfurlan** [comment]
@StefanoLazzaroni Giusto, sarà da modificare, ma credo che photo sarà la principale, mentre secondaryPhoto***s*** sarà un array di foto secondarie.
Comunque sì, è da sistemare anche questo

**Comment by StefanoLazzaroni** [comment]
![image](https://user-images.githubusercontent.com/44039735/110145214-7b017380-7dd9-11eb-8f48-40f128bc42a4.png)
Infatti, leggendo più avanti ne prevediamo al massimo 4

**Comment by ivanfurlan** [comment]
Dovrebbe essere tutto ok a partire da a6893a1
