### ISSUE TITLE
API /getTax

### ISSUE THREAD

**Issue by StefanoLazzaroni** [SWException/eml-be#3]
![image](https://user-images.githubusercontent.com/44039735/110213541-d2b6e200-7ea0-11eb-95c0-e1e5f1091e2a.png)

![image](https://user-images.githubusercontent.com/44039735/110213554-dd717700-7ea0-11eb-9949-937d07da9c44.png)

E' più un promemoria che Issue in se. L'implementazione non rispecchia l'AdR in quanto manca il campo descrizione
Opzioni:
1) modifichiamo adr
2) nella nuova implementazione scriviamo anche la descrizione

Oppure il campo nome è da ritenersi la descrizione? In tal caso dobbiamo sistemare la nomenclatura :)

**Comment by ivanfurlan** [comment]
modificato in 998e2328fe2caaaf0ab6189d1b6a0f899fee7b17 mettendo: id, value, description
