### ISSUE TITLE
API post/cart

### ISSUE THREAD

**Issue by ftrole** [SWException/eml-be#5]
- [ ]  **POST/cart** creazione ordine da un carrello di un utente (aggiungere ai dati del carrello "id ordine" e "totale", "indirizzi fatturazione", "ind. spedizione", stato ), vedi [qui ](https://docs.google.com/spreadsheets/d/19Vl-MX_jesE574azDKcaOA647iPO7xGl60xle0qSjg0/edit?usp=sharing)

Definizione openapi delle API legate agli ordini:
- [ ] GET/orders/{id}
- [ ] GET/orders
- [ ] POST/orders
- [ ] PATCH/orders

**Comment by mcanovese** [comment]
Viene demandato al collega **Michele** la definizione di un ID ordine efficace e con bassa possibilità di duplicazione nella fase di generazione, si prega di riflettere sul concetto di generazione al fine di ottenere un ID corto
