### ISSUE TITLE
API Categorie e prodotti 

### ISSUE THREAD

**Issue by ftrole** [SWException/eml-be#8]
- [ ] Implementazione API categorie
- [ ] Verifica API ordini
- [ ] Caricamento foto S3

**Comment by ivanfurlan** [comment]
@ftrole Nel branch `feature/products` ho aggiunto un controllo che i dati in input nel body quando si crea o modifica un prodotto rispettino il relativo schema definito in `src/products/schema.json`

**Comment by ftrole** [comment]
Ricevuto e recepito, mò do un occhio grazie
